/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello_word;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppWorks() {
        String[] args = {"Jan", "Malčák"};
        App.main(args);
    }
}
